[features]
seeds = true
skip-lint = false
[programs.localnet]
sol_gateway = "SCERbrcgSPwgkrJ7j4TABr17dhYzdgiwPZUSSfFPt8x"
[programs.devnet]
sol_gateway = "6CvJLL1q7A9vD97jHGtr8EX7LoaPEP51HH2ab2JLUn9m"

[registry]
url = "https://api.apr.dev"

[provider]
#cluster = "Localnet"
cluster = "devnet"
#cluster = "testnet"
#cluster = "mainnet"
wallet = "/home/shailesh/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
#test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/0_testing_macros.ts"

[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
program = "./deps/mpl-token-metadata/programs/token-metadata/target/deploy/mpl_token_metadata.so"

[toolchain]
anchor_version = "0.29.0"  # `anchor-cli` version to use
solana_version = "1.17.0" # Solana version to use
